import React from 'react';
import Hero from '../components/Hero';
import Programs from '../components/Programs';
import { Card, CardHeader, CardTitle, CardDescription, CardContent } from '../components/ui/card';
import { Button } from '../components/ui/button';

const Home = () => {
  const impactStats = [
    {
      number: "500+",
      label: "Youth Transformed",
      korean: "청년들의 변화",
      description: "Lives changed through our comprehensive programs"
    },
    {
      number: "85%",
      label: "Success Rate",
      korean: "성공률",
      description: "Of participants achieve their initial goals"
    },
    {
      number: "12",
      label: "Countries Reached",
      korean: "도달한 국가",
      description: "Global impact across multiple continents"
    },
    {
      number: "$2.5M+",
      label: "Economic Impact",
      korean: "경제적 영향",
      description: "Generated by our program graduates"
    }
  ];

  const missionAreas = [
    {
      title: "Emotional Healing",
      korean: "정서적 치유",
      icon: "❤️",
      description: "Addressing isolation and building healthy relationships through community connection and personal development."
    },
    {
      title: "Skill Development",
      korean: "역량 개발",
      icon: "🎯",
      description: "Teaching practical life skills, leadership abilities, and professional competencies for sustainable growth."
    },
    {
      title: "Financial Empowerment",
      korean: "경제적 역량 강화",
      icon: "💡",
      description: "Building financial literacy and entrepreneurial mindsets to achieve economic independence."
    },
    {
      title: "Global Community",
      korean: "글로벌 커뮤니티",
      icon: "🌐",
      description: "Creating connections across cultures and borders, fostering a worldwide network of empowered youth."
    }
  ];

  return (
    <div className="min-h-screen">
      {/* Hero Section */}
      <Hero />

      {/* Mission Areas */}
      <section className="py-20 bg-light-grey">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-16">
            <div className="mb-4">
              <span className="inline-block px-4 py-2 bg-golden-light/15 rounded-full text-golden-light font-noto-serif-kr text-sm font-semibold border border-golden-light/20">
                우리의 사명
              </span>
            </div>
            <h2 className="text-4xl lg:text-5xl font-bold font-sora mb-6 text-charcoal-gray">
              Our <span className="text-golden-light">Mission Areas</span>
            </h2>
            <p className="text-xl text-charcoal-gray/70 max-w-3xl mx-auto">
              We focus on holistic development that addresses the root causes of isolation 
              while building sustainable pathways to success.
            </p>
          </div>

          <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-8">
            {missionAreas.map((area, index) => (
              <Card key={index} className="text-center korean-shadow hover:shadow-xl transition-all duration-300 group animate-slide-up" style={{ animationDelay: `${index * 0.1}s` }}>
                <CardHeader>
                  <div className="text-5xl mb-4 group-hover:scale-110 transition-transform">
                    {area.icon}
                  </div>
                  <CardTitle className="text-lg mb-2 font-sora">
                    {area.title}
                  </CardTitle>
                  <div className="text-sm font-noto-serif-kr text-soft-orchid mb-4">
                    {area.korean}
                  </div>
                </CardHeader>
                <CardContent>
                  <CardDescription className="text-sm leading-relaxed">
                    {area.description}
                  </CardDescription>
                </CardContent>
              </Card>
            ))}
          </div>
        </div>
      </section>

      {/* Programs Overview */}
      <Programs />

      {/* Impact Statistics */}
      <section className="py-20 bg-gradient-to-r from-charcoal-gray via-charcoal-gray/95 to-charcoal-gray text-white">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-16">
            <h2 className="text-4xl lg:text-5xl font-bold font-sora mb-6">
              Our <span className="text-golden-light">Impact</span>
            </h2>
            <p className="text-xl text-white/80 font-noto-serif-kr">
              실제 변화를 만들어가고 있습니다
            </p>
          </div>

          <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-8">
            {impactStats.map((stat, index) => (
              <div key={index} className="text-center animate-fade-in" style={{ animationDelay: `${index * 0.2}s` }}>
                <div className="text-5xl lg:text-6xl font-bold font-sora text-golden-light mb-4">
                  {stat.number}
                </div>
                <div className="text-lg font-semibold mb-2 font-sora">
                  {stat.label}
                </div>
                <div className="text-sm text-hope-blue mb-3 font-noto-serif-kr">
                  {stat.korean}
                </div>
                <div className="text-sm text-white/70 leading-relaxed">
                  {stat.description}
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Call to Action */}
      <section className="py-20 bg-gradient-to-br from-hope-blue/5 to-emerald-growth/5">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 text-center">
          <div className="mb-8">
            <div className="text-6xl mb-6">🌱</div>
            <h2 className="text-4xl lg:text-5xl font-bold font-sora mb-6 text-charcoal-gray">
              Be Part of the <span className="text-emerald-growth">Change</span>
            </h2>
            <p className="text-xl text-charcoal-gray/70 mb-8 leading-relaxed">
              Whether you're a youth seeking transformation, a mentor ready to guide, 
              or a supporter wanting to make a difference – there's a place for you in our community.
            </p>
            <div className="font-noto-serif-kr text-soft-orchid mb-12">
              함께 만들어가는 희망의 여정
            </div>
          </div>

          <div className="grid md:grid-cols-3 gap-6 mb-12">
            <Card className="text-center p-6 korean-shadow hover:shadow-lg transition-shadow">
              <CardContent className="space-y-4">
                <div className="text-4xl">🚀</div>
                <h3 className="font-sora font-semibold">For Youth</h3>
                <p className="text-sm text-charcoal-gray/70">Ready to transform your life? Join our programs and start your journey.</p>
                <Button variant="hope" className="w-full">Apply Now</Button>
              </CardContent>
            </Card>

            <Card className="text-center p-6 korean-shadow hover:shadow-lg transition-shadow">
              <CardContent className="space-y-4">
                <div className="text-4xl">🤝</div>
                <h3 className="font-sora font-semibold">For Mentors</h3>
                <p className="text-sm text-charcoal-gray/70">Share your experience and guide the next generation of leaders.</p>
                <Button variant="growth" className="w-full">Volunteer</Button>
              </CardContent>
            </Card>

            <Card className="text-center p-6 korean-shadow hover:shadow-lg transition-shadow">
              <CardContent className="space-y-4">
                <div className="text-4xl">💝</div>
                <h3 className="font-sora font-semibold">For Supporters</h3>
                <p className="text-sm text-charcoal-gray/70">Help us reach more youth and expand our global impact.</p>
                <Button variant="golden" className="w-full">Donate</Button>
              </CardContent>
            </Card>
          </div>

          <div className="text-center">
            <p className="text-sm text-charcoal-gray/60 mb-6">
              Questions about how to get involved? We're here to help.
            </p>
            <Button variant="outline" size="lg">
              Contact Our Team
            </Button>
          </div>
        </div>
      </section>
    </div>
  );
};

export default Home;
